### ISSUE TITLE
FastForwards for services and deployments

### ISSUE THREAD

**Issue by srfrnk** [srfrnk/k9s#3]
**Is your feature request related to a problem? Please describe.**
While FastForwards are great for pod... `kubectl` also supports deployment, services etc.

**Describe the solution you'd like**
The annotation `k9scli.io/auto-portforwards` to be used when set on `v1/services`, `apps/v1/deployments`, `apps/v1/statefulsets`

**Describe alternatives you've considered**
Using a plugin...
```yaml
plugin:
  service-port-forward:
    description: Service Port Forward
    shortCut: Ctrl-F
    confirm: false
    background: true
    scopes:
      - services
    command: service-port-forward.sh
    args:
      - $CONTEXT
      - $NAMESPACE
      - $NAME
```

With script file `~/bin/service-port-forward.sh` (or anywhere in path):
```bash
#!/bin/bash
kubectl port-forward --context $1 -n $2 svc/$3 $(kubectl get -o jsonpath='{.metadata.annotations.k9scli\.io/auto-portforwards}' --context $1 -n $2 svc/$3)
sleep 10
```

Only issue there is I can't see the port forwarding active in K9s and can't terminate it (I could create another plugin for that... but still...)
