### ISSUE TITLE
Customize health indicators

### ISSUE THREAD

**Issue by srfrnk** [srfrnk/k9s#4]
Enable using JQ for health indication (row color) as done in dashboard for other objects e.g. CRDs but possibly builtin objects as well.

Possible solution, a new config file "health.yaml" with following schema:
```yaml
<GVR>:
  modified: <JQ QUERY STRING>
  added: <JQ QUERY STRING>
  pending: <JQ QUERY STRING>
  error: <JQ QUERY STRING>
  std: <JQ QUERY STRING>
  highlight: <JQ QUERY STRING>
  kill: <JQ QUERY STRING>
  completed: <JQ QUERY STRING>
```
